#!/usr/bin/env ruby
require 'rubygems'
require 'mysql2'

#m = Mysql2::Client.new(:host => 'localhost', :username => '', :password => '...')
m = Mysql2::Client.new(:database => 'test')

def suspicious?(rows)
	max = max_touched_rows(rows)
	return max && max > 10
end

def max_touched_rows(rows)
	max = nil
	rows.each do |row|
		if max.nil? || (row["rows"] && row["rows"] > max)
			max = row["rows"]
		end
	end
	return max
end

begin
	while !STDIN.eof?
		query = STDIN.readline.strip
		next if query.empty?
		result = m.query("explain #{query}")
		rows = result.to_a
		if suspicious?(rows)
			puts "#{max_touched_rows(rows)} rows - #{query}"
		end
	end
rescue EOFError
	exit 0
rescue Interrupt
	exit 1
end